# Generated by Django 6.0.1 on 2026-03-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='exam_name',
            new_name='exam',
        ),
    ]
