# Generated by Django 6.0.1 on 2026-03-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_exam_name_mark_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='score',
            new_name='marks',
        ),
    ]
