# Generated by Django 6.0.1 on 2026-03-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_score_mark_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='total',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
