# Generated by Django 6.0.1 on 2026-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_mark_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='priority',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
