# Generated by Django 6.0.1 on 2026-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_assignment_priority_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
